# This config file for Travis CI utilizes https://github.com/ros-planning/moveit_ci/ package.
sudo: required
dist: xenial  # distro used by Travis, moveit_ci uses the docker image's distro
services:
  - docker
language: cpp
cache: ccache
compiler: gcc

notifications:
  email:
    recipients:
      - 130s@2000.jukuin.keio.ac.jp
env:
  global:
    - ROS_DISTRO=melodic
    - ROS_REPO=ros
  matrix:
    - TEST="clang-format"
    - ROS_DISTRO=kinetic
    - ROS_DISTRO=melodic

before_script:
  - git clone -q --depth=1 https://github.com/ros-planning/moveit_ci.git .moveit_ci

script:
  - .moveit_ci/travis.sh
